namespace Wave.OpenXR
{
	public enum XrEnvironmentBlendMode
	{
		XR_ENVIRONMENT_BLEND_MODE_OPAQUE = 1,
		XR_ENVIRONMENT_BLEND_MODE_ADDITIVE = 2,
		XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND = 3,
		XR_ENVIRONMENT_BLEND_MODE_MAX_ENUM = int.MaxValue
	}
}
