namespace Wave.OpenXR
{
	public enum XrReferenceSpaceType
	{
		XR_REFERENCE_SPACE_TYPE_VIEW = 1,
		XR_REFERENCE_SPACE_TYPE_LOCAL = 2,
		XR_REFERENCE_SPACE_TYPE_STAGE = 3,
		XR_REFERENCE_SPACE_TYPE_UNBOUNDED_MSFT = 1000038000,
		XR_REFERENCE_SPACE_TYPE_COMBINED_EYE_VARJO = 1000121000,
		XR_REFERENCE_SPACE_TYPE_MAX_ENUM = int.MaxValue
	}
}
