namespace Wave.OpenXR
{
	public enum XrSessionState
	{
		XR_SESSION_STATE_UNKNOWN = 0,
		XR_SESSION_STATE_IDLE = 1,
		XR_SESSION_STATE_READY = 2,
		XR_SESSION_STATE_SYNCHRONIZED = 3,
		XR_SESSION_STATE_VISIBLE = 4,
		XR_SESSION_STATE_FOCUSED = 5,
		XR_SESSION_STATE_STOPPING = 6,
		XR_SESSION_STATE_LOSS_PENDING = 7,
		XR_SESSION_STATE_EXITING = 8,
		XR_SESSION_STATE_MAX_ENUM = int.MaxValue
	}
}
