namespace Wave.OpenXR.FacialTracking
{
	public enum XrEyeExpressionHTC
	{
		XR_EYE_EXPRESSION_LEFT_BLINK_HTC = 0,
		XR_EYE_EXPRESSION_LEFT_WIDE_HTC = 1,
		XR_EYE_EXPRESSION_RIGHT_BLINK_HTC = 2,
		XR_EYE_EXPRESSION_RIGHT_WIDE_HTC = 3,
		XR_EYE_EXPRESSION_LEFT_SQUEEZE_HTC = 4,
		XR_EYE_EXPRESSION_RIGHT_SQUEEZE_HTC = 5,
		XR_EYE_EXPRESSION_LEFT_DOWN_HTC = 6,
		XR_EYE_EXPRESSION_RIGHT_DOWN_HTC = 7,
		XR_EYE_EXPRESSION_LEFT_OUT_HTC = 8,
		XR_EYE_EXPRESSION_RIGHT_IN_HTC = 9,
		XR_EYE_EXPRESSION_LEFT_IN_HTC = 10,
		XR_EYE_EXPRESSION_RIGHT_OUT_HTC = 11,
		XR_EYE_EXPRESSION_LEFT_UP_HTC = 12,
		XR_EYE_EXPRESSION_RIGHT_UP_HTC = 13,
		XR_EYE_EXPRESSION_MAX_ENUM_HTC = 14
	}
}
